FROM centos:latest
MAINTAINER sangeetadhikari1234@gmail.com
RUN yum install -y httpd \
  zip \
 unzip
ADD https://www.allrecipes.com/recipe/72483/biriyani/
WORKDIR /var/www/html
RUN unzip Kindle.zip
RUN cp -rvf markups-kindle/* .
RUN rm -rf _MACOSX markups-kindle kindle.zip
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
EXPOSE 80
 
